export type HeroVideo = {
  id: string;
  src: string;
  label: string;
  objectPosition: string;
};

const local = (path: string) => path;

/** All UI media prefers light WebP sources (regenerated by scripts/make-webp.mjs). */
export const brandAssets = {
  logo: local("/assets/brand/nautic-logo.webp"),
  heroPoster: local("/assets/hero/nh-nature-poster.webp"),
  favicon: local("/favicon.png"),
} as const;

export const decorativeAssets = {
  leafSage: local("/assets/decorative/leaf-sage.webp"),
  leafSage2: local("/assets/decorative/leaf-sage-2.webp"),
  leafForest: local("/assets/decorative/leaf-forest.webp"),
  leafGold: local("/assets/decorative/leaf-gold.webp"),
} as const;

export const sectionAssets = {
  tassoBloodTest: local("/assets/diagnostics/tasso-blood-test.webp"),
  philosophy: local("/assets/philosophy/philosophy.webp"),
  longevity: local("/assets/philosophy/longevity.webp"),
  ctaStretch: local("/assets/cta/cta-stretch.webp"),
  clinic: local("/assets/pages/clinic.webp"),
} as const;

export const treatmentImages = {
  tirzepatide: local("/assets/treatments/tirzepatide.webp"),
  semaglutide: local("/assets/treatments/semaglutide.webp"),
  semaglutideEditorial: local("/assets/treatments/semaglutide.webp"),
  hormone: local("/assets/treatments/hormone.jpg"),
  nad: local("/assets/treatments/nad.jpg"),
  sermorelin: local("/assets/treatments/sermorelin.jpg"),
  performance: local("/assets/treatments/performance.jpg"),
  cognitive: local("/assets/treatments/cognitive.jpg"),
  overall: local("/assets/treatments/overall.jpg"),
} as const;

export const journeyImages = {
  goal: local("/assets/journey/journey-goal.webp"),
  assessment: local("/assets/journey/journey-assessment.webp"),
  review: local("/assets/journey/journey-review.webp"),
  consult: local("/assets/journey/journey-consult.webp"),
  support: local("/assets/journey/journey-support.webp"),
} as const;

export const journalImages = {
  hero: local("/assets/journal/journal-hero.jpg"),
  cellular: local("/assets/journal/journal-cellular.jpg"),
  recovery: local("/assets/journal/program-recovery.jpg"),
  nutrition: local("/assets/journal/journal-nutrition.jpg"),
  sleep: local("/assets/journal/journal-sleep.jpg"),
  weight: local("/assets/journal/program-weight.jpg"),
} as const;

/** Only two hero clips — keeps first paint light vs four ~10MB files. */
export const heroVideos: HeroVideo[] = [
  {
    id: "nature-01",
    src: local("/assets/hero/nh-nature-01.mp4"),
    label: "Green leaves with dew moving gently in soft morning light",
    objectPosition: "50% 35%",
  },
  {
    id: "nature-02",
    src: local("/assets/hero/nh-nature-02.mp4"),
    label: "Premium unbranded wellness vials in a clean minimal setting",
    objectPosition: "50% 35%",
  },
];

export const heroTiming = {
  rotateMs: 4200,
  fadeMs: 1000,
  splashLeadMs: 900,
} as const;
