export type HeroVideo = {
  id: string;
  src: string;
  label: string;
  objectPosition: string;
};

const local = (path: string) => path;

/** All UI media prefers light WebP sources (regenerated by scripts/make-webp.mjs). */
export const brandAssets = {
  logo: local("/assets/brand/nautic-logo.webp"),
  /** Original PNG used by nautichealth.com hero logo splash. */
  logoPng: local("/assets/brand/nautic-logo.png"),
  /** Light poster for faster LCP; same frame as nautichealth.com. */
  heroPoster: local("/assets/hero/nh-nature-poster.webp"),
  favicon: local("/favicon.png"),
} as const;

export const decorativeAssets = {
  leafSage: local("/assets/decorative/leaf-sage.webp"),
  leafSage2: local("/assets/decorative/leaf-sage-2.webp"),
  leafForest: local("/assets/decorative/leaf-forest.webp"),
  leafGold: local("/assets/decorative/leaf-gold.webp"),
} as const;

export const sectionAssets = {
  tassoBloodTest: local("/assets/diagnostics/tasso-blood-test.webp"),
  philosophy: local("/assets/philosophy/philosophy.webp"),
  longevity: local("/assets/philosophy/longevity.webp"),
  ctaStretch: local("/assets/cta/cta-stretch-new1.webp"),
  clinic: local("/assets/pages/clinic.webp"),
  couple: local("/assets/pages/couple.webp"),
} as const;

export const treatmentImages = {
  tirzepatide: local("/assets/treatments/tirzepatide.webp"),
  semaglutide: local("/assets/treatments/semaglutide.webp"),
  semaglutideEditorial: local("/assets/treatments/semaglutide.webp"),
  hormone: local("/assets/treatments/hormone.webp"),
  nad: local("/assets/treatments/nad.webp"),
  sermorelin: local("/assets/treatments/sermorelin.webp"),
  performance: local("/assets/treatments/performance.webp"),
  cognitive: local("/assets/treatments/cognitive.webp"),
  overall: local("/assets/treatments/overall.webp"),
} as const;

/** Exact live-site journey UI mockups (homepage Patient Journey). */
export const journeyImages = {
  goal: local("/assets/journey/journey-goal-CDDjGLt3.jpg"),
  assessment: local("/assets/journey/journey-assessment-CqRN--0_.jpg"),
  review: local("/assets/journey/journey-review-wJWLbzH0.jpg"),
  consult: local("/assets/journey/journey-consult-D9l62zAb.jpg"),
  support: local("/assets/journey/journey-support-BcU8Kk4T.jpg"),
} as const;

export const journalImages = {
  hero: local("/assets/journal/journal-hero.webp"),
  cellular: local("/assets/journal/journal-cellular.webp"),
  recovery: local("/assets/journal/program-recovery.webp"),
  nutrition: local("/assets/journal/journal-nutrition.webp"),
  sleep: local("/assets/journal/journal-sleep.webp"),
  weight: local("/assets/journal/program-weight.webp"),
} as const;

/** Four hero clips — same carousel as nautichealth.com. */
export const heroVideos: HeroVideo[] = [
  {
    id: "nature-01",
    src: local("/assets/hero/nh-nature-01.mp4"),
    label: "Green leaves with dew moving gently in soft morning light",
    objectPosition: "50% 35%",
  },
  {
    id: "nature-02",
    src: local("/assets/hero/nh-nature-02.mp4"),
    label: "Premium unbranded wellness vials in a clean minimal setting",
    objectPosition: "50% 35%",
  },
  {
    id: "nature-03",
    src: local("/assets/hero/nh-nature-03.mp4"),
    label: "Wellness vials blended with soft greenery and light reflections",
    objectPosition: "50% 35%",
  },
  {
    id: "nature-04",
    src: local("/assets/hero/nh-nature-04.mp4"),
    label: "A serene composition of water, greenery and wellness vials",
    objectPosition: "50% 35%",
  },
];

/** Timing aligned to nautichealth.com hero carousel. */
export const heroTiming = {
  rotateMs: 3400,
  fadeMs: 1200,
  splashLeadMs: 900,
} as const;
